
CREATE TABLE IF NOT EXISTS StashContents (
    StashId char(64),
    ItemId char(64),
    Hash bit(128),
    League smallint,
    Price smallint,
    Currency smallint,
    ItemType smallint,
    AddedTime timestamp with time zone,
    SoldTime timestamp with time zone,
    SeenTime timestamp with time zone
);
CREATE INDEX ON StashContents (StashId);
CREATE UNIQUE INDEX ON StashContents (ItemId);


CREATE TABLE IF NOT EXISTS BodyItems (
    ItemId char(64),
    Hash bit(128),
    Sockets varchar(12),
    Corrupted bool,
    Armour smallint,
    Evasion smallint,
    EnergyShield smallint,
    ReqLevel smallint,
    ReqStr smallint,
    ReqDex smallint ,
    ReqInt smallint ,
    Life smallint ,
    Mana smallint ,
    Strength smallint ,
    Dexterity smallint ,
    Intelligence smallint ,
    FireResist smallint ,
    ColdResist smallint ,
    LightningResist smallint ,
    ChaosResist smallint ,
    LifeRegen smallint, /* divide by 10 to get in-game number */
    StunRecovery smallint,
    PhysReflect smallint ,
    AvoidIgnite smallint ,
    AvoidFreeze smallint ,
    AvoidShock smallint ,
    GrantedSkillId smallint ,
    GrantedSkillLevel smallint ,
    CannotBeKnockedBack bool ,
    SocketedGemLevel smallint ,
    SocketedVaalGemLevel smallint ,
    MaxFireResist smallint ,
    MaxColdResist smallint ,
    MaxLightningResist smallint ,
    MaxChaosResist smallint ,
    ManaMultiplier smallint
);
CREATE INDEX ON BodyItems (ItemId);

CREATE TABLE IF NOT EXISTS HelmetItems (
    ItemId char(64),
    Hash bit(128),
    Sockets varchar(8),
    Corrupted bool,
    Armour smallint,
    Evasion smallint,
    EnergyShield smallint,
    ReqLevel smallint,
    ReqStr smallint,
    ReqDex smallint ,
    ReqInt smallint ,
    Life smallint ,
    Mana smallint ,
    Strength smallint ,
    Dexterity smallint ,
    Intelligence smallint ,
    FireResist smallint ,
    ColdResist smallint ,
    LightningResist smallint ,
    ChaosResist smallint ,
    SocketedMinionGems smallint,
    ItemRarity smallint,
    Accuracy smallint ,
    StunRecovery smallint ,
    PhysReflect smallint,
    LifeRegen smallint ,
    LightRadius smallint ,
    ManaShield smallint ,
    EnemiesCannotLeech bool ,
    GrantedSkillId smallint,
    GrantedSkillLevel smallint,
    SocketedVaalGemLevel smallint ,
    MinionDamage smallint ,
    SupportGemId smallint ,
    SupportGemLevel smallint
);
CREATE INDEX ON HelmetItems (ItemId);

CREATE TABLE IF NOT EXISTS BootsItems (
    ItemId char(64),
    Hash bit(128),
    Sockets varchar(8),
    Corrupted bool,
    Armour smallint,
    Evasion smallint,
    EnergyShield smallint,
    ReqLevel smallint,
    ReqStr smallint,
    ReqDex smallint ,
    ReqInt smallint ,
    Life smallint ,
    Mana smallint ,
    Strength smallint ,
    Dexterity smallint ,
    Intelligence smallint ,
    FireResist smallint ,
    ColdResist smallint ,
    LightningResist smallint ,
    ChaosResist smallint ,
    ItemRarity smallint ,
    MoveSpeed smallint ,
    LifeRegen smallint ,
    StunRecovery smallint,
    DodgeAttacks smallint ,
    GrantedSkillId smallint ,
    GrantedSkillLevel smallint ,
    CannotBeKnockedBack bool,
    SocketedGemLevel smallint ,
    SocketedVaalGemLevel smallint ,
    MaxFrenzyCharges smallint
)
CREATE INDEX ON BootsItems (ItemId);

CREATE TABLE IF NOT EXISTS GlovesItems (
    ItemId char(64),
    Hash bit(128),
    Sockets varchar(8),
    Corrupted bool,
    Armour smallint,
    Evasion smallint,
    EnergyShield smallint,
    ReqLevel smallint,
    ReqStr smallint,
    ReqDex smallint ,
    ReqInt smallint ,
    Life smallint ,
    Mana smallint ,
    Strength smallint ,
    Dexterity smallint ,
    Intelligence smallint ,
    FireResist smallint ,
    ColdResist smallint ,
    LightningResist smallint ,
    ChaosResist smallint ,
    Accuracy smallint ,
    AttackSpeed smallint ,
    AddedEleAttackDamage smallint ,
    AddedPhysAttackDamage smallint ,
    ItemRarity smallint ,
    LifeLeech smallint ,
    ManaLeech smallint,
    LifeGainOnHit smallint ,
    LifeGainOnKill smallint ,
    LifeRegen smallint ,
    ManaGainOnKill smallint ,
    StunRecovery smallint ,
    CurseOnHitId smallint ,
    CurseOnHitLevel smallint ,
    GrantedSkillId smallint ,
    GrantedSkillLevel smallint ,
    SocketedGemLevel smallint ,
    SocketedVaalGemLevel smallint ,
    CastSpeed smallint ,
    SupportGemId smallint ,
    SupportGemLevel smallint
);
CREATE INDEX ON GlovesItems (ItemId);

CREATE TABLE ShieldItems (
    ItemId char(64),
    Hash bit(128),
    Sockets varchar(8),
    Corrupted bool,
    Armour smallint,
    Evasion smallint,
    EnergyShield smallint,
    ReqLevel smallint,
    ReqStr smallint,
    ReqDex smallint ,
    ReqInt smallint ,
    Life smallint ,
    Mana smallint ,
    Strength smallint ,
    Dexterity smallint ,
    Intelligence smallint ,
    FireResist smallint ,
    ColdResist smallint ,
    LightningResist smallint ,
    ChaosResist smallint ,
    BlockChance smallint ,
    PhysReflect smallint ,
    StunRecovery smallint ,
    SocketedMeleeGemLevel smallint ,
    SocketedChaosGemLevel smallint ,
    SocketedFireGemLevel smallint ,
    SocketedColdGemLevel smallint ,
    SocketedLightningGemLevel smallint ,
    LifeRegen smallint ,
    ManaRegen smallint ,
    IncreasedSpellDamage smallint ,
    SpellCritChance smallint ,
    AvoidIgnite smallint ,
    GrantedSkillId smallint ,
    GrantedSkillLevel smallint ,
    SocketedGemLevel smallint ,
    SocketedVaalGemLevel smallint ,
    CastSpeed smallint ,
    ManaShield smallint ,
    PhysDamageReduction smallint ,
    SpellBlock smallint
);
CREATE INDEX ON ShieldItems (ItemId);

CREATE TABLE RingItems (
    ItemId char(64),
    Hash bit(128),
    Corrupted bool,
    Sockets varchar(2),
    ReqLevel smallint ,
    DoubledInBreach bool,
    Evasion smallint ,
    Strength smallint ,
    Dexterity smallint ,
    Intelligence smallint ,
    Life smallint ,
    Mana smallint ,
    EnergyShield smallint ,
    FireResist smallint ,
    ColdResist smallint ,
    LightningResist smallint ,
    ChaosResist smallint ,
    Accuracy smallint ,
    AddedPhysAttackDamage smallint ,
    AddedFireAttackDamage smallint ,
    AddedColdAttackDamage smallint ,
    AddedLightningAttackDamage smallint ,
    AddedChaosAttackDamage smallint ,
    IncreasedEleDamage smallint ,
    IncreasedWeaponEleDamage smallint ,
    IncreasedFireDamage smallint ,
    IncreasedColdDamage smallint ,
    IncreasedLightningDamage smallint ,
    CritChance smallint ,
    ItemRarity smallint,
    LifeLeech smallint ,
    ManaLeech smallint ,
    AttackSpeed smallint ,
    CastSpeed smallint ,
    LifeGainOnHit smallint ,
    LifeGainOnKill smallint ,
    LifeRegen smallint ,
    LightRadius smallint ,
    ManaGainOnKill smallint ,
    ManaRegen smallint ,
    AvoidFreeze smallint ,
    GrantedSkillId smallint ,
    GrantedSkillLevel smallint ,
    ManaGainOnHit smallint ,
    DamageToMana smallint
);
CREATE INDEX ON RingItems(ItemId);

CREATE TABLE AmuletItems (
    ItemId char(64),
    Hash bit(128),
    Corrupted bool,
    ReqLevel smallint ,
    Strength smallint ,
    Dexterity smallint ,
    Intelligence smallint ,
    Life smallint ,
    Mana smallint ,
    EnergyShield smallint ,
    LifeRegen smallint ,
    ManaRegen smallint ,
    FireResist smallint ,
    ColdResist smallint ,
    LightningResist smallint ,
    ChaosResist smallint ,
    AddedPhysAttackDamage smallint ,
    AddedFireAttackDamage smallint ,
    AddedColdAttackDamage smallint ,
    AddedLightningAttackDamage smallint ,
    IncreasedEnergyShield smallint ,
    IncreasedEvasion smallint ,
    IncreasedArmour smallint ,
    IncreasedWeaponEleDamage smallint ,
    IncreasedSpellDamage smallint ,
    IncreasedFireDamage smallint ,
    IncreasedColdDamage smallint ,
    IncreasedLightningDamage smallint ,
    CritChance smallint ,
    CritMulti smallint ,
    Accuracy smallint ,
    ItemRarity smallint ,
    LifeLeech smallint ,
    ManaLeech smallint ,
    CastSpeed smallint ,
    LifeGainOnHit smallint ,
    LifeGainOnKill smallint ,
    ManaGainOnKill smallint ,
    ExtraCurse smallint ,
    AvoidIgnite smallint ,
    AvoidFreeze smallint ,
    BlockChance smallint ,
    LifeLeechCold smallint ,
    LifeLeechFire smallint ,
    LifeLeechLightning smallint ,
    GrantedSkillId smallint ,
    GrantedSkillLevel smallint,
    AttackSpeed smallint ,
    MaxFrenzCharges smallint ,
    MinionDamage smallint ,
    MoveSpeed smallint ,
    ManaShield smallint ,
    PhysDamageReduction smallint ,
    SpellBlock smallint
);
CREATE INDEX ON AmuletItems(ItemId);

COMMIT;
