
CREATE TABLE IF NOT EXISTS StashContents (
    StashId char(64) not null,
    ItemId char(64) not null,
    Hash uuid not null,
    League smallint not null,
    Price smallint not null,
    Currency smallint not null,
    ItemType smallint not null,
    AddedTime timestamp with time zone not null,
    SoldTime timestamp with time zone not null,
    SeenTime timestamp with time zone not null,
    X smallint not null,
    Y smallint not null,
    W smallint not null,
    H smallint not null
);
CREATE UNIQUE INDEX ON StashContents (ItemId);


CREATE TABLE IF NOT EXISTS Players (
    PlayerId bigint PRIMARY KEY,
    AccountName varchar(50) not null,
    League smallint not null,
    Predictions jsonb
);
CREATE UNIQUE INDEX ON Players (AccountName, League);

CREATE TABLE IF NOT EXISTS BodyItems (
    ItemId char(64),
    Hash uuid,
    Sockets varchar(12),
    Corrupted bool,

    ReqLevel smallint,
    ReqStr smallint,
    ReqDex smallint ,
    ReqInt smallint ,

    Armour smallint,
    Evasion smallint,
    EnergyShield smallint,

    AvoidIgnite smallint ,
    AvoidFreeze smallint ,
    AvoidShock smallint ,
    CannotBeKnockedBack bool ,
    ChaosResist smallint ,
    ColdResist smallint ,
    Dexterity smallint ,
    FireResist smallint ,
    GrantedSkillId smallint ,
    GrantedSkillLevel smallint ,
    Intelligence smallint ,
    Life smallint ,
    LifeRegen smallint, /* divide by 10 to get in-game number */
    LightningResist smallint ,
    Mana smallint ,
    ManaMultiplier smallint,
    MaxResists smallint ,
    MoveSpeed smallint,
    PhysReflect smallint ,
    SocketedGemLevel smallint ,
    SocketedVaalGemLevel smallint ,
    SpellDamage smallint ,
    Strength smallint ,
    StunRecovery smallint
);
CREATE INDEX ON BodyItems (ItemId);

CREATE TABLE IF NOT EXISTS HelmetItems (
    ItemId char(64),
    Hash uuid,
    Sockets varchar(8),
    Corrupted bool,

    ReqLevel smallint,
    ReqStr smallint,
    ReqDex smallint ,
    ReqInt smallint ,

    Armour smallint,
    Evasion smallint,
    EnergyShield smallint,

    Accuracy smallint ,
    ChaosResist smallint ,
    ColdResist smallint ,
    Dexterity smallint ,
    EnemiesCannotLeech bool ,
    FireResist smallint ,
    GrantedSkillId smallint,
    GrantedSkillLevel smallint,
    Intelligence smallint ,
    ItemRarity smallint,
    Life smallint ,
    LifeRegen smallint ,
    LightningResist smallint ,
    LightRadius smallint ,
    Mana smallint ,
    ManaShield smallint ,
    MinionDamage smallint ,
    PhysReflect smallint,
    SocketedMinionGemLevel smallint,
    SocketedVaalGemLevel smallint ,
    Strength smallint ,
    StunRecovery smallint ,
    SupportedByCastOnCrit smallint ,
    SupportedByCastOnStun smallint

);
CREATE INDEX ON HelmetItems (ItemId);

CREATE TABLE IF NOT EXISTS BootsItems (
    ItemId char(64),
    Hash uuid,
    Sockets varchar(8),
    Corrupted bool,
    Armour smallint,
    Evasion smallint,
    EnergyShield smallint,
    ReqLevel smallint,
    ReqStr smallint,
    ReqDex smallint ,
    ReqInt smallint ,
    Life smallint ,
    Mana smallint ,
    Strength smallint ,
    Dexterity smallint ,
    Intelligence smallint ,
    FireResist smallint ,
    ColdResist smallint ,
    LightningResist smallint ,
    ChaosResist smallint ,
    ItemRarity smallint ,
    MoveSpeed smallint ,
    LifeRegen smallint ,
    StunRecovery smallint,
    DodgeAttacks smallint ,
    GrantedSkillId smallint ,
    GrantedSkillLevel smallint ,
    CannotBeKnockedBack bool,
    SocketedGemLevel smallint ,
    SocketedVaalGemLevel smallint ,
    MaxFrenzyCharges smallint
);
CREATE INDEX ON BootsItems (ItemId);

CREATE TABLE IF NOT EXISTS GlovesItems (
    ItemId char(64),
    Hash uuid,
    Sockets varchar(8),
    Corrupted bool,

    ReqLevel smallint,
    ReqStr smallint,
    ReqDex smallint ,
    ReqInt smallint ,

    Armour smallint,
    Evasion smallint,
    EnergyShield smallint,

    Accuracy smallint ,
    AddedColdAttackDamage smallint ,
    AddedFireAttackDamage smallint ,
    AddedLightningAttackDamage smallint ,
    AddedPhysAttackDamage smallint ,
    AttackSpeed smallint ,
    CastSpeed smallint ,
    ChaosResist smallint ,
    ColdResist smallint ,
    Dexterity smallint ,
    EleWeaknessOnHit smallint ,
    FireResist smallint ,
    GrantedSkillId smallint ,
    GrantedSkillLevel smallint ,
    Intelligence smallint ,
    ItemRarity smallint ,
    Life smallint ,
    LifeGainOnHit smallint ,
    LifeGainOnKill smallint ,
    LifeLeech smallint ,
    LifeRegen smallint ,
    LightningResist smallint ,
    Mana smallint ,
    ManaGainOnKill smallint ,
    ManaLeech smallint,
    MeleeDamage smallint,
    ProjectileAttackDamage smallint,
    SocketedGemLevel smallint ,
    SocketedVaalGemLevel smallint ,
    SpellDamage smallint,
    Strength smallint ,
    StunRecovery smallint ,
    SupportedByCastOnCrit smallint ,
    SupportedByCastOnStun smallint,
    TempChainsOnHit smallint ,
    VulnerabilityOnHit smallint
);
CREATE INDEX ON GlovesItems (ItemId);

CREATE TABLE ShieldItems (
    ItemId char(64),
    Hash uuid,
    Sockets varchar(8),
    Corrupted bool,
    Armour smallint,
    Evasion smallint,
    EnergyShield smallint,
    ReqLevel smallint,
    ReqStr smallint,
    ReqDex smallint ,
    ReqInt smallint ,
    Life smallint ,
    Mana smallint ,
    Strength smallint ,
    Dexterity smallint ,
    Intelligence smallint ,
    FireResist smallint ,
    ColdResist smallint ,
    LightningResist smallint ,
    ChaosResist smallint ,
    BlockChance smallint ,
    PhysReflect smallint ,
    StunRecovery smallint ,
    SocketedMeleeGemLevel smallint ,
    SocketedChaosGemLevel smallint ,
    SocketedFireGemLevel smallint ,
    SocketedColdGemLevel smallint ,
    SocketedLightningGemLevel smallint ,
    LifeRegen smallint ,
    ManaRegen smallint ,
    IncreasedSpellDamage smallint ,
    SpellCritChance smallint ,
    AvoidIgnite smallint ,
    GrantedSkillId smallint ,
    GrantedSkillLevel smallint ,
    SocketedGemLevel smallint ,
    SocketedVaalGemLevel smallint ,
    CastSpeed smallint ,
    ManaShield smallint ,
    PhysDamageReduction smallint ,
    SpellBlock smallint
);
CREATE INDEX ON ShieldItems (ItemId);

CREATE TABLE RingItems (
    ItemId char(64),
    Hash uuid,
    Corrupted bool,
    Sockets varchar(2),
    ReqLevel smallint NOT NULL DEFAULT 0,

    Accuracy smallint  NOT NULL DEFAULT 0,
    AddedChaosAttackDamage smallint  NOT NULL DEFAULT 0,
    AddedColdAttackDamage smallint  NOT NULL DEFAULT 0,
    AddedFireAttackDamage smallint NOT NULL  DEFAULT 0,
    AddedLightningAttackDamage smallint  NOT NULL DEFAULT 0,
    AddedPhysAttackDamage smallint  NOT NULL DEFAULT 0,
    AttackSpeed smallint  NOT NULL DEFAULT 0,
    AvoidFreeze smallint  NOT NULL DEFAULT 0,
    CastSpeed smallint  NOT NULL DEFAULT 0,
    ChaosResist smallint NOT NULL  DEFAULT 0,
    ColdResist smallint NOT NULL  DEFAULT 0,
    CritChance smallint  NOT NULL DEFAULT 0,
    DamageToMana smallint  NOT NULL DEFAULT 0
    Dexterity smallint  NOT NULL DEFAULT 0,
    DoubledInBreach bool NOT NULL DEFAULT false,
    EnergyShield smallint  NOT NULL DEFAULT 0,
    Evasion smallint  NOT NULL DEFAULT 0,
    FireResist smallint  NOT NULL DEFAULT 0,
    GrantedSkillId smallint  NOT NULL DEFAULT 0,
    GrantedSkillLevel smallint  NOT NULL DEFAULT 0,
    IncreasedAccuracy smallint NOT NULL DEFAULT 0,  -- new
    IncreasedColdDamage smallint  NOT NULL DEFAULT 0,
    IncreasedEleDamage smallint  NOT NULL DEFAULT 0,
    IncreasedFireDamage smallint NOT NULL  DEFAULT 0,
    IncreasedLightningDamage smallint  NOT NULL DEFAULT 0,
    IncreasedWeaponEleDamage smallint  NOT NULL DEFAULT 0,
    Intelligence smallint  NOT NULL DEFAULT 0,
    ItemRarity smallint  NOT NULL DEFAULT 0,
    Life smallint NOT NULL  DEFAULT 0,
    LifeGainOnHit smallint NOT NULL  DEFAULT 0,
    LifeGainOnKill smallint  NOT NULL DEFAULT 0,
    LifeLeech smallint NOT NULL  DEFAULT 0,
    LifeRegen smallint  NOT NULL DEFAULT 0,
    LightningResist smallint  NOT NULL DEFAULT 0,
    LightRadius smallint  NOT NULL DEFAULT 0,
    Mana smallint NOT NULL  DEFAULT 0,
    ManaGainOnHit smallint NOT NULL DEFAULT 0,
    ManaGainOnKill smallint  NOT NULL DEFAULT 0,
    ManaLeech smallint  NOT NULL DEFAULT 0,
    ManaRegen smallint  NOT NULL DEFAULT 0,
    SocketedGemLevel smallint NOT NULL DEFAULT 0,
    Strength smallint  NOT NULL DEFAULT 0,

);
CREATE INDEX ON RingItems(ItemId);

CREATE TABLE AmuletItems (
    ItemId char(64),
    Hash uuid,
    Corrupted bool,
    ReqLevel smallint ,

    Accuracy smallint ,
    AdditionalCurses smallint ,
    AddedColdAttackDamage smallint ,
    AddedFireAttackDamage smallint ,
    AddedLightningAttackDamage smallint ,
    AddedPhysAttackDamage smallint ,
    AttackSpeed smallint ,
    AvoidFreeze smallint ,
    AvoidIgnite smallint ,
    BlockChance smallint ,
    IncreasedEnergyShield smallint ,
    CastSpeed smallint ,
    ChaosResist smallint ,
    ColdResist smallint ,
    CritChance smallint ,
    CritMulti smallint ,
    DamageToMana smallint ,
    Dexterity smallint ,
    EnergyShield smallint ,
    FireResist smallint ,
    GrantedSkillId smallint ,
    GrantedSkillLevel smallint,
    IncreasedArmour smallint ,
    IncreasedColdDamage smallint ,
    IncreasedEvasion smallint ,
    IncreasedFireDamage smallint ,
    IncreasedLifeRegen smallint ,
    IncreasedLightningDamage smallint ,
    IncreasedSpellDamage smallint ,
    IncreasedWeaponEleDamage smallint ,
    Intelligence smallint ,
    ItemRarity smallint ,
    Life smallint ,
    LifeGainOnHit smallint ,
    LifeGainOnKill smallint ,
    LifeLeech smallint ,
    LifeLeechCold smallint ,
    LifeLeechFire smallint ,
    LifeLeechLightning smallint ,
    LifeRegen smallint ,
    LightningResist smallint ,
    Mana smallint ,
    ManaGainOnKill smallint ,
    ManaLeech smallint ,
    ManaRegen smallint ,
    MaxFrenzyCharges smallint ,
    MaxResists smallint,
    MinionDamage smallint ,
    MoveSpeed smallint ,
    PhysDamageReduction smallint ,
    SpellBlock smallint,
    SpellDamage smallint ,
    Strength smallint

);
CREATE INDEX ON AmuletItems(ItemId);

COMMIT;
